// Common Vietnamese banks (short name — full name)
export const VN_BANKS: { code: string; name: string }[] = [
  { code: "VCB", name: "Vietcombank - NH TMCP Ngoại thương Việt Nam" },
  { code: "VTB", name: "VietinBank - NH TMCP Công thương Việt Nam" },
  { code: "BIDV", name: "BIDV - NH TMCP Đầu tư và Phát triển Việt Nam" },
  { code: "AGR", name: "Agribank - NH Nông nghiệp và PT Nông thôn" },
  { code: "TCB", name: "Techcombank - NH TMCP Kỹ thương Việt Nam" },
  { code: "MB", name: "MB Bank - NH TMCP Quân đội" },
  { code: "ACB", name: "ACB - NH TMCP Á Châu" },
  { code: "VPB", name: "VPBank - NH TMCP Việt Nam Thịnh Vượng" },
  { code: "STB", name: "Sacombank - NH TMCP Sài Gòn Thương Tín" },
  { code: "TPB", name: "TPBank - NH TMCP Tiên Phong" },
  { code: "SHB", name: "SHB - NH TMCP Sài Gòn - Hà Nội" },
  { code: "HDB", name: "HDBank - NH TMCP Phát triển TP.HCM" },
  { code: "VIB", name: "VIB - NH TMCP Quốc tế Việt Nam" },
  { code: "MSB", name: "MSB - NH TMCP Hàng Hải Việt Nam" },
  { code: "OCB", name: "OCB - NH TMCP Phương Đông" },
  { code: "SEA", name: "SeABank - NH TMCP Đông Nam Á" },
  { code: "LPB", name: "LPBank - NH TMCP Lộc Phát (LienVietPostBank)" },
  { code: "EIB", name: "Eximbank - NH TMCP Xuất nhập khẩu Việt Nam" },
  { code: "NAB", name: "NamABank - NH TMCP Nam Á" },
  { code: "BAB", name: "BacABank - NH TMCP Bắc Á" },
  { code: "ABB", name: "ABBank - NH TMCP An Bình" },
  { code: "PVB", name: "PVcomBank - NH TMCP Đại Chúng Việt Nam" },
  { code: "SGB", name: "Saigonbank - NH TMCP Sài Gòn Công Thương" },
  { code: "KLB", name: "KienLongBank - NH TMCP Kiên Long" },
  { code: "VAB", name: "VietABank - NH TMCP Việt Á" },
  { code: "VBB", name: "Vietbank - NH TMCP Việt Nam Thương Tín" },
  { code: "BVB", name: "BaoVietBank - NH TMCP Bảo Việt" },
  { code: "NCB", name: "NCB - NH TMCP Quốc Dân" },
  { code: "SCB", name: "SCB - NH TMCP Sài Gòn" },
  { code: "DAB", name: "DongABank - NH TMCP Đông Á" },
  { code: "PGB", name: "PGBank - NH TMCP Xăng dầu Petrolimex" },
  { code: "VCCB", name: "VietCapitalBank - NH Bản Việt" },
  { code: "CAKE", name: "Cake by VPBank" },
  { code: "TIMO", name: "Timo" },
  { code: "UB", name: "Ubank by VPBank" },
  { code: "SCBVN", name: "Standard Chartered Việt Nam" },
  { code: "HSBC", name: "HSBC Việt Nam" },
  { code: "SHBVN", name: "Shinhan Bank Việt Nam" },
  { code: "WRB", name: "Woori Bank Việt Nam" },
  { code: "UOB", name: "UOB Việt Nam" },
  { code: "PBVN", name: "Public Bank Việt Nam" },
  { code: "CITI", name: "Citibank Việt Nam" },
  { code: "IVB", name: "Indovina Bank" },
  { code: "VRB", name: "Vietnam-Russia Joint Venture Bank (VRB)" },
];
